name: Maven Package

on:
  release:
    types: [created]

jobs:
  build:

    runs-on: windows-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Maven
      run: mvnw.cmd -B package --file pom.xml
      # If you don't have the 'mvnw.cmd' wrapper, replace the command with 'mvn.cmd -B package --file pom.xml'

    - name: Publish to GitHub Packages Apache Maven
      run: mvnw.cmd deploy -s $GITHUB_WORKSPACE/settings.xml
      # If you don't have the 'mvnw.cmd' wrapper, replace the command with 'mvn.cmd deploy -s $GITHUB_WORKSPACE/settings.xml'
      env:
        GITHUB_TOKEN: ${{ github.token }}
